server:
  address: 127.0.0.1
  port: 5050
  tomcat:
    basedir: /tmp/tomcat
  session:
    timeout: 300

spring:
  datasource:
    master:
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/timemachine?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/timemachine?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
    redis: # redis配置
      host: localhost
      password: 123456
      port: 8379
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 1
  servlet:
    multipart:
      max-file-size: 1MB      # 单个文件
      max-request-size: 10MB   # 一次请求
  mvc:
    static-path-pattern: /image/**
  resources:
    static-locations: file:/Users/william/SpringBoot/springbootweb-images
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  thymeleaf:
    prefix: classpath:/templates/
    suffix: html
    mode: HTML5
    encoding: UTF-8
    # 热部署文件，页面不产生缓存，及时更新
    cache: false

mybatis:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.example.springbootweb.dao.module

logging:
  path: /Users/william/SpringBoot/log

# 接口文档
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

# 文件
sbwImagesPath: /Users/william/SpringBoot/springbootweb-images
# https://www.toyaml.com/index.html
#
#
#primary: true