server:
  address: 192.168.0.1
  port: 8080
  session:
    timeout: 300

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/timemachine?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    redis: # redis配置
      host: localhost
      password: 123456
      port: 8379
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 1
  servlet:
    multipart:
      max-file-size: 1MB      # 单个文件
      max-request-size: 10MB   # 一次请求
  mvc:
    static-path-pattern: /image/**
  resources:
    static-locations: file:/home/{your.dir}/timeMachine-case-images

mybatis:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.example.springbootweb.dao.module

#showSql
logging:
  level:
    com:
      example:
        springbootweb:
          dao:
            mapper : debug

# 日志
log:
  charset: UTF-8
  level: INFO
  path: ./logs
  # pattern: %red([%d{'MM-dd HH:mm:ss,SSS',GMT+8:00}]) %green(%level) %highlight([%thread]) %boldMagenta(%logger{0}[%line]) - %cyan(%msg%n)

# 接口文档
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

# 文件
tma.imagesPath: /home/{your.dir}/timeMachine-case-images

# https://www.toyaml.com/index.html